"""Add is_active to maladies, districts and centres_sante

Revision ID: c89a76cc914c
Revises: e03ffa20c75c
Create Date: 2025-11-16 10:44:27.432924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89a76cc914c'
down_revision: Union[str, Sequence[str], None] = 'e03ffa20c75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centres_sante', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('districts', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('districts', 'is_active')
    op.drop_column('centres_sante', 'is_active')
    # ### end Alembic commands ###
